language: cpp
compiler:
  - gcc
  - clang
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9 libconfig++-dev libcurl4-openssl-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 60
script: make && make test
